experiment:
    name: my_first_experiment
    version: 1

#######################################################################################
#######################################################################################

# FETCH DATASET FROM CASSANDRA
dataset:
    db_table: shohel.refined_stock_data
    stock_symbol: AAPL

    # FORMAT: %Y-%m-%d %H:%M:%S
    timestamps:
        start: '2019-01-01 00:00:00'
        end: '2019-01-10 00:00:00'

    # PROVIDE A MIN ROW COUNT FOR THE DATASET
    # FOR SANITY CHECKING
    min_length_threshold: 10

    # EXPECTED ROW SCHEMA
    expected_schema:
        symbol: str
        timestamp: str
        open: float
        close: float
        high: float
        low: float
        volume: int

#######################################################################################
#######################################################################################

# APPLY FEATURES
feature_engineering:
    features:
        -   feature_name: stochastic_k
            feature_params:
                window_size: 5
            output_column: sk5
        -   feature_name: stochastic_k
            feature_params:
                window_size: 14
            output_column: sk14
    
    # AFTER ALL FEATURES ARE APPLIED
    # SHOULD WE DROP ROWS WITH NANs?
    drop_nans: True

#######################################################################################
#######################################################################################

# APPLY FEATURES
segmentation:
    - train: 0.75
    - test: 0.1
    - validate: 0.15

#######################################################################################
#######################################################################################

# TODO: TEST MODEL TRAINING
# TODO: TEST MODEL TRAINING
# TODO: TEST MODEL TRAINING

#######################################################################################
#######################################################################################

# TRADING STRATEGY
trading_strategy:
    base_strategy:
        batch_size: 3
        transaction_fee: 2
        init_capital: 100
        init_stocks: 0
        # allow_short_selling: True

    custom_strategy:
        strategy_name: weighted_strategy
        strategy_params:
            buy_weight: 1.05
            sell_weight: 0.95

    # IDEA
    # custom_strategies:
    #     -   strategy_name: weighted_strategy
    #         strategy_params:
    #             buy_weight: 1.05
    #             sell_weight: 0.95
    #     -   strategy_name: other_strat
    #         strategy_params:
    #             foo: bar
    #     -   strategy_name: third_strat
    #         strategy_params:
    #             biz: baz